import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Distance Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-center p-2">
          <section className="flex flex-col w-full max-w-[1000px] bg-white rounded-2xl items-center justify-between p-8 shadow">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
